# Generated by Django 4.0.2 on 2022-02-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_session', models.DateField()),
                ('semester_type', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester')], max_length=4)),
            ],
        ),
    ]
