# Generated by Django 4.0.2 on 2022-02-13 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('course_title', models.CharField(max_length=30)),
                ('course_unit', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'CourseDetails',
            },
        ),
        migrations.CreateModel(
            name='FacultyTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(choices=[('MON', 'MONDAY'), ('TUE', 'TUESDAY'), ('WED', 'WEDNESDAY'), ('THUR', 'THURSDAY'), ('FRI', 'FRIDAY')], max_length=4)),
                ('time', models.TimeField()),
                ('venue', models.CharField(choices=[('NLT1', 'NEW LECTURE THEATRE 1'), ('NLT2', 'NEW LECTURE THEATRE 2'), ('NLT3', 'NEW LECTURE THEATRE 3'), ('BAS', 'BASEMENT CLASSROOM')], max_length=100)),
                ('course', models.ManyToManyField(to='timetable.CourseDetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'StudentTimetable',
            },
        ),
    ]
