# Generated by Django 4.0.2 on 2022-02-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursedetails',
            options={'verbose_name_plural': 'CourseDetails'},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'verbose_name_plural': 'Timetable'},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='course',
        ),
        migrations.AddField(
            model_name='timetable',
            name='course',
            field=models.ManyToManyField(to='timetable.CourseDetails'),
        ),
    ]
